### ISSUE TITLE
Need to update to new version of brq to fix this.body.buffer bug

### ISSUE THREAD

**Issue by bucko13** [bcoin-org/bcurl#2]
bcurl breaks in browser version when doing get requests because brq expects a `this.body`. Fixed on master of brq but need to publish that and upgrade the dependency.

**Comment by nodar-chkuaselidze** [comment]
Is this resolved ? @bucko13

**Comment by bucko13** [comment]
no, not yet. In the places where I need it, I just enforce brq #master branch in the package.json.
